#!/bin/bash
forever start -e /var/nethive/ws_err.log -o /var/nethive/ws_out.log ws.js 
forever start -o /var/nethive/downloader_out.log -e /var/nethive/downloader_err.log  downloader.js 
forever start -o /var/nethive/updater_out.log -e /var/nethive/updater_err.log  updater.js  
forever start -o /var/nethive/regl_out.log -e /var/nethive/regl_err.log registerEventListener.js
forever start -o /var/nethive/labelEventOut.log -e /var/nethive/labelEventErr.log labelEventListener.js
python3 kafka-communicator.py
